export const indonesianWords = [
  { word: 'apel', category: 'buah', language: 'id' },
  { word: 'lemari', category: 'benda', language: 'id' },
  { word: 'ikan', category: 'hewan', language: 'id' },
  { word: 'nanas', category: 'buah', language: 'id' },
  { word: 'sekolah', category: 'tempat', language: 'id' },
  { word: 'harimau', category: 'hewan', language: 'id' },
  { word: 'udang', category: 'hewan', language: 'id' },
  { word: 'gajah', category: 'hewan', language: 'id' },
  { word: 'hotel', category: 'tempat', language: 'id' },
  { word: 'langit', category: 'alam', language: 'id' },
  { word: 'tinggi', category: 'sifat', language: 'id' },
  { word: 'ibu', category: 'keluarga', language: 'id' },
  { word: 'uang', category: 'benda', language: 'id' },
  { word: 'gelas', category: 'benda', language: 'id' },
  { word: 'singa', category: 'hewan', language: 'id' },
  { word: 'ayam', category: 'hewan', language: 'id' },
  { word: 'mobil', category: 'kendaraan', language: 'id' },
  { word: 'laut', category: 'alam', language: 'id' },
  { word: 'taman', category: 'tempat', language: 'id' },
  { word: 'naga', category: 'fantasi', language: 'id' }
]

export const englishWords = [
  { word: 'apple', category: 'fruit', language: 'en' },
  { word: 'elephant', category: 'animal', language: 'en' },
  { word: 'tiger', category: 'animal', language: 'en' },
  { word: 'rose', category: 'flower', language: 'en' },
  { word: 'eagle', category: 'bird', language: 'en' },
  { word: 'egg', category: 'food', language: 'en' },
  { word: 'guitar', category: 'instrument', language: 'en' },
  { word: 'rabbit', category: 'animal', language: 'en' },
  { word: 'table', category: 'furniture', language: 'en' },
  { word: 'engine', category: 'machine', language: 'en' },
  { word: 'horse', category: 'animal', language: 'en' },
  { word: 'earth', category: 'nature', language: 'en' },
  { word: 'hat', category: 'clothing', language: 'en' },
  { word: 'tree', category: 'nature', language: 'en' },
  { word: 'notebook', category: 'stationery', language: 'en' },
  { word: 'king', category: 'royalty', language: 'en' },
  { word: 'garden', category: 'place', language: 'en' },
  { word: 'nurse', category: 'profession', language: 'en' },
  { word: 'nest', category: 'nature', language: 'en' },
  { word: 'dog', category: 'animal', language: 'en' },
  // extra English words
  { word: 'sun', category: 'nature', language: 'en' },
  { word: 'night', category: 'time', language: 'en' },
  { word: 'tea', category: 'drink', language: 'en' },
  { word: 'amber', category: 'color', language: 'en' },
  { word: 'river', category: 'nature', language: 'en' },
  { word: 'rocket', category: 'vehicle', language: 'en' },
  { word: 'tablet', category: 'device', language: 'en' },
  { word: 'lamp', category: 'furniture', language: 'en' },
  { word: 'pen', category: 'stationery', language: 'en' },
  { word: 'noodle', category: 'food', language: 'en' }
]

